In [20]:
import pandas as pd
from sodapy import Socrata

In [30]:
client = Socrata('data.sfgov.org',
                 '0r5XNOm1weRyhpaOSPLTJ7TWN',
                  username='sohambhagwat2@gmail.com',
                  password="SoData007#")

results = client.get("fpux-q53t", limit=200000)

In [31]:
results_df = pd.DataFrame.from_records(results)
results_df

,activity_period,activity_period_start_date,operating_airline,operating_airline_iata_code,published_airline,published_airline_iata_code,geo_summary,geo_region,landing_aircraft_type,aircraft_body_type,aircraft_manufacturer,aircraft_model,aircraft_version,landing_count,total_landed_weight,data_as_of,data_loaded_at
0,199907,1999-07-01T00:00:00.000,ATA Airlines,TZ,ATA Airlines,TZ,Domestic,US,Passenger,Narrow Body,Boeing,727,200,4,618000,2024-06-20T13:00:23.000,2024-06-22T15:02:34.000
1,199907,1999-07-01T00:00:00.000,ATA Airlines,TZ,ATA Airlines,TZ,Domestic,US,Passenger,Narrow Body,Boeing,757,NaN,78,15444000,2024-06-20T13:00:23.000,2024-06-22T15:02:34.000
2,199907,1999-07-01T00:00:00.000,ATA Airlines,TZ,ATA Airlines,TZ,Domestic,US,Passenger,Wide Body,Lockheed,L1011,0,71,25418000,2024-06-20T13:00:23.000,2024-06-22T15:02:34.000
3,199907,1999-07-01T00:00:00.000,ATA Airlines,TZ,ATA Airlines,TZ,Domestic,US,Passenger,Wide Body,Lockheed,L1011,100,1,368000,2024-06-20T13:00:23.000,2024-06-22T15:02:34.000
4,199907,1999-07-01T00:00:00.000,Aeroflot Russian International Airlines,NaN,Aeroflot Russian International Airlines,NaN,International,Europe,Passenger,Wide Body,Boeing,767,0,9,2879955,2024-06-20T13:00:23.000,2024-06-22T15:02:34.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41876,202404,2024-04-01T00:00:00.000,Virgin Atlantic,VS,Virgin Atlantic,VS,International,Europe,Passenger,Wide Body,Boeing,B789,-,56,23800000,2024-06-20T13:00:25.000,2024-06-22T15:02:34.000
41877,202404,2024-04-01T00:00:00.000,WestJet Airlines,WS,WestJet Airlines,WS,International,Canada,Passenger,Narrow Body,Boeing,B38M,-,4,611200,2024-06-20T13:00:25.000,2024-06-22T15:02:34.000
41878,202404,2024-04-01T00:00:00.000,WestJet Airlines,WS,WestJet Airlines,WS,International,Canada,Passenger,Narrow Body,Boeing,B737,-,5,646000,2024-06-20T13:00:25.000,2024-06-22T15:02:34.000
41879,202404,2024-04-01T00:00:00.000,WestJet Airlines,WS,WestJet Airlines,WS,International,Canada,Passenger,Narrow Body,Boeing,B738,-,10,1463000,2024-06-20T13:00:25.000,2024-06-22T15:02:34.000
41880,202404,2024-04-01T00:00:00.000,ZIPAIR Tokyo Inc,ZG,ZIPAIR Tokyo Inc,ZG,International,Asia,Passenger,Wide Body,Boeing,B788,-,30,11400000,2024-06-20T13:00:25.000,2024-06-22T15:02:34.000

In [34]:
results_df.dtypes

activity_period                object
activity_period_start_date     object
operating_airline              object
operating_airline_iata_code    object
published_airline              object
published_airline_iata_code    object
geo_summary                    object
geo_region                     object
landing_aircraft_type          object
aircraft_body_type             object
aircraft_manufacturer          object
aircraft_model                 object
aircraft_version               object
landing_count                  object
total_landed_weight            object
data_as_of                     object
data_loaded_at                 object
dtype: object